### ISSUE TITLE
active_records_views table in db/schema.rb

### ISSUE THREAD

**Issue by twe4ked** [jasoncodes/activerecord_views#16]
Hey Jason :)

I'm using `db/schema.rb` in a project and if I drop my database and run migrations the schema file loses the `active_record_views` table. If I then access the view class name from `rails console` and run another migration the table comes back. Is this expected behaviour? I wonder if it has anything to do with the issues I'm having in #15.

**Comment by jasoncodes** [comment]
Hey, Odin. :)

I first thought this was the problem as every other app I use `active_record_views` in has `config.active_record.schema_format = :sql` and it was an obvious configuration difference. I gave this a test though and nothing changed.

**Comment by jasoncodes** [comment]
To answer your question, this is expected behaviour. `activerecord_views` is designed to bootstrap the metadata table if it doesn’t already exist. As long as that metadata table and what views are present are in sync, everything’s fine.

**Comment by jasoncodes** [comment]
Related: There was an issue with SQL schema format dumps on Rails 4.2. Fixed and added coverage in 0.0.12.
